### ISSUE TITLE
-nothreads causes a segmentation fault

### ISSUE THREAD

**Issue by carloshellin** [propagamap/Signal-Server#1]
It may be interesting to have this argument running correctly during the whole execution of the program in order to be able to debug more easily without threads. In the meantime, we can launch the command `-exec set scheduler-locking on` in the debug console, but the debugging is not quite complete.

https://github.com/propagamap/Signal-Server/blob/163b8ce57c7753a4408aea5c6e78727a67856f22/.vscode/launch.json#L13

**Comment by liu-hanli** [comment]
DONE
This is a program problem, a important function `void init_processed()` in "los.cc" is not called when the option "no_thread" is applied.

**Comment by carloshellin** [comment]
https://github.com/propagamap/Signal-Server/pull/5
