### ISSUE TITLE
Implement GetElevation to get elevations from openelevationservice

### ISSUE THREAD

**Issue by carloshellin** [propagamap/Signal-Server#3]
Make an HTTP request to openelevationservice to get the elevation in location.lat and location.lot.
Check that the old function (_GetElevation) doesn't do something else extra to take into account like with the point positions.
Better than programming with the socket library of each operating system, use a library that is in C and cross-platform. For example: https://www.libhttp.org/

I think this way is simpler and faster than trying with the .sdf files (and their various conversions...)

https://github.com/propagamap/Signal-Server/blob/163b8ce57c7753a4408aea5c6e78727a67856f22/src/main.cc#L329

**Comment by franchu7** [comment]
MINE
