### ISSUE TITLE
Implement a new argument to the command and be able to name this file with the db output

### ISSUE THREAD

**Issue by carloshellin** [propagamap/Signal-Server#4]
It would be interesting to have for convenience and comparisons a new argument defining this filename used to save the raw results like the -o for the .ppm file, This actually came already programmed, but the filename was always 0.

https://github.com/propagamap/Signal-Server/blob/163b8ce57c7753a4408aea5c6e78727a67856f22/src/main.cc#L1189

The results that are stored in this file can be seen in:
https://github.com/propagamap/Signal-Server/blob/163b8ce57c7753a4408aea5c6e78727a67856f22/src/models/los.cc#L611

https://github.com/propagamap/Signal-Server/blob/163b8ce57c7753a4408aea5c6e78727a67856f22/src/models/los.cc#L621

**Comment by liu-hanli** [comment]
DONE
Parameter `-o-plo`, filename is optional, the default value will be concat the base output name with ".txt".

**Comment by carloshellin** [comment]
https://github.com/propagamap/Signal-Server/pull/5
